### ISSUE TITLE
make winapi's HANDLE compatible with std's HANDLE

### ISSUE THREAD

**Issue by pearzl** [retep998/winapi-rs#874] opened 2020-04-01 18:12 UTC
I notice that `core::ffi::c_void` is exist since rust 1.30, we don't need to define a new `c_void` by ourself when `std` feature is not enable.
Do we have plan to do this?

**Comment by retep998** [comment] 2020-04-01 23:08
Duplicate of https://github.com/retep998/winapi-rs/issues/771

**Closed as completed by retep998** 2020-04-01 23:08 UTC
Labels: duplicate
