### ISSUE TITLE
Derive everything for the ENUM! generated types

### ISSUE THREAD

**Issue by kvark** [retep998/winapi-rs#263] opened 2016-03-01 14:05 UTC
`#[derive(Clone, PartialEq, Eq, Hash, Debug)]` - at least that
This is an easy one. Please make it happen before releasing a new version.

**Comment by retep998** [comment] 2016-03-01 14:11
All of those except for `Hash` are already implemented https://github.com/retep998/winapi-rs/blob/master/src/macros.rs#L210

However, due to long compile times caused by all the codegen from all those impls I'm considering making the representation just be a plain integer in winapi 0.3 so I don't have to impl any traits.

**Comment by retep998** [comment] 2016-03-05 02:02
Should be fixed by https://github.com/retep998/winapi-rs/commit/04c79789cb577a1fc0db7e8df741403dd4d4fc1e

**Comment by retep998** [comment] 2016-08-15 21:47
`ENUM!` now creates simple integer constants so no traits need to be derived.

**Closed by retep998** 2016-08-15 21:47 UTC
